; Note: This file should be generated by an external tool
;       but making it is outside of the scope of this project
.feature c_comments
.export level_tiles
.export level


.segment "CODE"
; Indices to the metatile definition array
level_tiles:
.byte $00, $01, $02, $03, $04, $05, $06, $07
.byte $08, $09, $0A, $0C, $0D, $0F, $10, $11

; Indices to the level tiles array
level:
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $E0
.byte $00, $00, $00, $00, $00, $00, $09, $AA
.byte $00, $00, $00, $00, $00, $00, $0B, $CC
.byte $00, $00, $00, $00, $00, $70, $0B, $CC
.byte $00, $00, $00, $00, $00, $80, $0B, $CC
.byte $00, $00, $00, $07, $00, $80, $0B, $CC
.byte $00, $D0, $00, $08, $00, $80, $0B, $CC
.byte $22, $22, $30, $08, $00, $80, $0B, $CC
.byte $45, $55, $60, $08, $00, $80, $0B, $CC
.byte $45, $55, $60, $08, $00, $80, $0B, $CC
.byte $45, $55, $60, $08, $00, $80, $0B, $CC
.byte $45, $55, $60, $08, $00, $80, $0B, $CC
