; Note: This file should be generated by an external tool
;       but making it is outside of the scope of this project
.feature c_comments
.export level

.segment "CODE"

level:
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00
.byte $00, $00, $00, $00, $00, $00, $09, $AA
.byte $00, $00, $00, $00, $00, $00, $0C, $DD
.byte $00, $00, $00, $00, $00, $07, $0C, $DD
.byte $00, $00, $00, $00, $00, $08, $0C, $DD
.byte $00, $00, $00, $00, $70, $08, $0C, $DD
.byte $00, $00, $00, $00, $80, $08, $0C, $DD
.byte $22, $22, $30, $00, $80, $08, $0C, $DD
.byte $45, $55, $60, $00, $80, $08, $0C, $DD
.byte $45, $55, $60, $00, $80, $08, $0C, $DD
.byte $45, $55, $60, $00, $80, $08, $0C, $DD
.byte $45, $55, $60, $00, $80, $08, $0C, $DD
