.feature c_comments
.segment "CHARS"

; mktile - loads a tile from $path
;          defines CHR ID as tiles_$name_id in the current scope

.macro mktile name, path
    .ident(.sprintf("tiles_%s_id", name)) = (* - tiles)/16
    .incbin path
.endmacro

tiles:
mktile "empty", "assets/chr/empty.chr"
mktile "grass", "assets/chr/grass.chr"
mktile "ice", "assets/chr/ice.chr"
mktile "sign", "assets/chr/sign.chr"
mktile "chest", "assets/chr/chest.chr"
mktile "platform", "assets/chr/platform.chr"
mktile "player", "assets/chr/player.chr"

.segment "CODE"

; Note: This file contains a lot of magic numbers.
; Metatile definitions should be generated by an
; external tool, not by hand!

.import palettes_green_id: zeropage
.import palettes_blue_id: zeropage
.import palettes_orange_id: zeropage
.import palettes_bw_id: zeropage

.export metatiles
.export tiles_grass
.export tiles_ice
.export tiles_sign
.export tiles_chest

.struct Metatile
    tileid_1    .byte
    tileid_2    .byte
    tileid_3    .byte
    tileid_4    .byte
    palette_id  .byte
;    collider_fn .word
.endstruct

nop
nop
nop
nop
nop
nop
nop
nop
nop

metatiles:
; AIR METATILE
; ----------------------

; $00
air:
.byte tiles_empty_id
.byte tiles_empty_id
.byte tiles_empty_id
.byte tiles_empty_id
.byte <palettes_blue_id
; .word collider_air

; GRASS METATILE
; ----------------------

tiles_grass:
; $01
grass_top_left:

.byte tiles_grass_id
.byte tiles_grass_id + 1
.byte tiles_grass_id + 3
.byte tiles_grass_id + 4
.byte <palettes_green_id
;.word collider_simple_block
    
; $02
grass_top_middle:
.byte tiles_grass_id + 1
.byte tiles_grass_id + 1
.byte tiles_grass_id + 4
.byte tiles_grass_id + 4
.byte <palettes_green_id
;.word collider_simple_block
    
; $03
grass_top_right:
.byte tiles_grass_id + 1
.byte tiles_grass_id + 2
.byte tiles_grass_id + 4
.byte tiles_grass_id + 5
.byte <palettes_green_id
;.word collider_simple_block
    
; $04
grass_middle_left:
.byte tiles_grass_id + 6
.byte tiles_grass_id + 7
.byte tiles_grass_id + 6
.byte tiles_grass_id + 8
.byte <palettes_green_id
;.word collider_simple_block

; $05
grass_middle_middle:
.byte tiles_grass_id + 8
.byte tiles_grass_id + 7
.byte tiles_grass_id + 7
.byte tiles_grass_id + 8
.byte <palettes_green_id
;.word collider_simple_block

; $06
grass_middle_right:
.byte tiles_grass_id + 8
.byte tiles_grass_id + 9
.byte tiles_grass_id + 7
.byte tiles_grass_id + 9
.byte <palettes_green_id
;.word collider_simple_block

; $07
grass_single_top:
.byte tiles_grass_id
.byte tiles_grass_id + 2
.byte tiles_grass_id + 3
.byte tiles_grass_id + 5
.byte <palettes_green_id

; $08
grass_single_middle:
.byte tiles_grass_id + 6
.byte tiles_grass_id + 9
.byte tiles_grass_id + 6
.byte tiles_grass_id + 9
.byte <palettes_green_id

; ICE METATILE
; ----------------------

; $09
tiles_ice:
ice_top_left:
.byte tiles_ice_id
.byte tiles_ice_id + 1
.byte tiles_ice_id + 3
.byte tiles_ice_id + 4
.byte <palettes_blue_id
;.word collider_slippery

; $0A
ice_top_middle:
.byte tiles_ice_id + 1
.byte tiles_ice_id + 1
.byte tiles_ice_id + 4
.byte tiles_ice_id + 4
.byte <palettes_blue_id
;.word collider_slippery

; $0B
ice_top_right:
.byte tiles_ice_id + 1
.byte tiles_ice_id + 2
.byte tiles_ice_id + 4
.byte tiles_ice_id + 5
.byte <palettes_blue_id
;.word collider_slippery

; $0C
ice_middle_left:
.byte tiles_ice_id + 6
.byte tiles_ice_id + 7
.byte tiles_ice_id + 6
.byte tiles_ice_id + 8
.byte <palettes_blue_id
;.word collider_slippery

; $0D
ice_middle_middle:
.byte tiles_ice_id + 8
.byte tiles_ice_id + 7
.byte tiles_ice_id + 7
.byte tiles_ice_id + 8
.byte <palettes_blue_id
;.word collider_slippery

; $0E
ice_middle_right:
.byte tiles_ice_id + 8
.byte tiles_ice_id + 9
.byte tiles_ice_id + 7
.byte tiles_ice_id + 9
.byte <palettes_blue_id
;.word collider_slippery

; SIGN METATILE
; ----------------------
; $0F
tiles_sign:
.byte tiles_sign_id
.byte tiles_sign_id + 1
.byte tiles_sign_id + 2
.byte tiles_sign_id + 3
.byte <palettes_orange_id
;.word collider_sign

; CHEST METATILE
; ----------------------
tiles_chest:
; $10
.byte tiles_chest_id
.byte tiles_chest_id + 1
.byte tiles_chest_id + 2
.byte tiles_chest_id + 3
.byte <palettes_orange_id

; DEBUG
; ----------------------
tiles_debug:
; $11
.byte tiles_chest_id
.byte tiles_chest_id + 1
.byte tiles_chest_id + 2
.byte tiles_chest_id + 3
.byte <palettes_bw_id
;.word collider_chest
